blank_issues_enabled: false
contact_links:
  - name: paddy74-portfolio Community Support
    url: https://github.com/paddy74/paddy74.github.io/discussions
    about: Please ask and answer questions here.
